sudo: required

services:
  - docker

before_install:
  - docker build -t malaika/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run malaika/react-test npm test -- --coverage

after_success:
  - docker build -t malaika/multi-client:latest ./client
  - docker build -t malaika/multi-nginx:latest ./nginx
  - docker build -t malaika/multi-server:latest ./server
  - docker build -t malaika/multi-worker:latest ./worker

  # Log into the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push the created images up to Docker Hub
  - docker push malaika/multi-client:latest
  - docker push malaika/multi-nginx:latest
  - docker push malaika/multi-server:latest
  - docker push malaika/multi-worker:latest

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-321358705221
  bucket_path: docker-multi
  on:
    master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY